<?php
$ethnicitys = array(
	"NZ European/Pakeha",
	"African",
	"Australian",
	"British/Irish",
	"Cambodian",
	"Chinese",
	"Cook Island Maori",
	"Dutch",
	"Fijian",
	"Filipino",
	"German",
	"Greek",
	"Indian",
	"Italian",
	"Japanese",
	"Korean",
	"Latin American",
	"Middle Eastern",
	"New Zealand Maori",
	"Niuean",
	"Polish",
	"Samoan",
	"South Slav",
	"Sri Lankan",
	"Tokelauan",
	"Tongan",
	"Vietnamese",
	"Other",
	"Other Asian",
	"Other European",
	"Other Pacific Island Groups",
	"Other Southeast Asian"
);
$maoriIwi = array(
	"Aotea",
	"Hapu Affiliated to More Than One Iwi",
	"Hauraki (Coromandel) Region, not further defined",
	"Hauraki / Pare Hauraki",
	"Horouta",
	"Kati Mamoe",
	"Kurahaupo",
	"Mahuru",
	"Mamari",
	"Manawatu/Horowhenua/Te Whanganui-a-Tara(Manawatu/Horowhenua/Wellington)Regionnfd",
	"Mataatua",
	"Moriori",
	"Muaupoko",
	"Muriwhenua",
	"Nga Rauru",
	"Nga Ruahine",
	"Ngai Tahu / Kai Tahu",
	"Ngai Tai (Hauraki)",
	"Ngai Tai (Tauranga Moana/Mataatua)",
	"Ngai Takoto",
	"Ngai Tamanuhiri",
	"Ngaiterangi",
	"Ngapuhi",
	"Ngapuhi ki Whaingaroa-Ngati Kahu ki Whaingaroa",
	"Ngati Apa (Rangitikei)",
	"Ngati Apa ki Te Ra To",
	"Ngati Apa, region unspecified",
	"Ngati Awa",
	"Ngati Hako",
	"Ngati Haua (Taumarunui)",
	"Ngati Haua (Waikato)",
	"Ngati Haua, region unspecified",
	"Ngati Hauiti",
	"Ngati Hei",
	"Ngati Kahu",
	"Ngati Kahungunu ki Heretaunga",
	"Ngati Kahungunu ki Tamakinui a Rua",
	"Ngati Kahungunu ki Tamatea",
	"Ngati Kahungunu ki Te Wairoa",
	"Ngati Kahungunu ki Te Whanganui-a-Orotu",
	"Ngati Kahungunu ki Wairarapa",
	"Ngati Kahungunu, region unspecified",
	"Ngati Kauwhata",
	"Ngati Koata",
	"Ngati Kuia",
	"Ngati Kuri",
	"Ngati Manawa",
	"Ngati Maniapoto",
	"Ngati Maru (Hauraki)",
	"Ngati Maru (Taranaki)",
	"Ngati Maru, region unspecified",
	"Ngati Mutunga (Taranaki)",
	"Ngati Mutunga (Wharekauri/Chatham Islands)",
	"Ngati Mutunga, region unspecified",
	"Ngati Pahauwera",
	"Ngati Paoa",
	"Ngati Pikiao (Te Arawa)",
	"Ngati Porou",
	"Ngati Porou ki Harataunga ki Mataora",
	"Ngati Pukenga",
	"Ngati Pukenga ki Waiau",
	"Ngati Rahiri Tumutumu",
	"Ngati Rakaipaaka",
	"Ngati Ranginui",
	"Ngati Rangiteaorere (Te Arawa)",
	"Ngati Rangitihi (Te Arawa)",
	"Ngati Rangiwewehi (Te Arawa)",
	"Ngati Rarua",
	"Ngati Raukawa (Horowhenua/Manawatu)",
	"Ngati Raukawa (Waikato)",
	"Ngati Raukawa, region unspecified",
	"Ngati Ruanui",
	"Ngati Tahu-Ngati Whaoa (Te Arawa)",
	"Ngati Tama (Taranaki)",
	"Ngati Tama (Te Waipounamu/South Island)",
	"Ngati Tama ki Te Upoko o Te Ika (Te Whanganui-a-Tara/Wellington)",
	"Ngati Tama, region unspecified",
	"Ngati Tamatera",
	"Ngati Tara Tokanui",
	"Ngati Toa, region unspecified",
	"Ngati Toarangatira (Te Waipounamu/South Island)",
	"Ngati Toarangatira (Te Whanganui-a-Tara/Wellington)",
	"Ngati Tuwharetoa",
	"Ngati Wai",
	"Ngati Whakaue (Te Arawa)",
	"Ngati Whanaunga",
	"Ngati Whare",
	"Ngati Whatua",
	"Ngatokimatawhaorua",
	"Nukutere",
	"Pakakohi",
	"Patukirikiri",
	"Rangitane (Manawatu)",
	"Rangitane (Te Matau-a-Maui/Hawke's Bay/Wairarapa)",
	"Rangitane (Te Waipounamu/South Island)",
	"Rangitane, region unspecified",
	"Rongomaiwahine (Te Mahia)",
	"Rongowhakaata",
	"Tainui",
	"Takitimu",
	"Tangahoe",
	"Tapuika (Te Arawa)",
	"Taranaki",
	"Taranaki (Taranaki) Region, not further defined",
	"Tarawhai (Te Arawa)",
	"Tauranga Moana",
	"Tauranga Moana/Mataatua (Bay of Plenty) Region, not further defined",
	"Te Aitanga-a-Mahaki",
	"Te Arawa",
	"Te Arawa/Taupo (Rotorua/Taupo) Region, not further defined",
	"Te Ati Haunui-a-Paparangi",
	"Te Atiawa (Taranaki)",
	"Te Atiawa (Te Waipounamu/South Island)",
	"Te Atiawa (Te Whanganui-a-Tara/Wellington)",
	"Te Atiawa ki Whakarongotai",
	"Te Atiawa, region unspecified",
	"Te Aupouri",
	"Te Kawerau",
	"Te Matau-a-Maui/Wairarapa (Hawke's Bay/Wairarapa) Region, not further defined",
	"Te Rarawa",
	"Te Roroa",
	"Te Tai Rawhiti (East Coast) Region, not further defined",
	"Te Tai Tokerau/Tamaki-makaurau (Northland/Auckland) Region, not further defined",
	"Te Tauihu o Te Waka a Maui",
	"Te Uri-o-Hau",
	"Te Waipounamu/Wharekauri (South Island/Chatham Islands) Region, nfd",
	"Te Whanau-a-Apanui",
	"Tokomaru",
	"Tuhoe",
	"Tuhourangi (Te Arawa)",
	"Turanganui a Kiwa",
	"Uenuku-Kopako (Te Arawa)",
	"Waikato",
	"Waikato/Te Rohe Potae (Waikato/King Country) Region, not further defined",
	"Waitaha (Te Arawa)",
	"Waitaha (Te Waipounamu/South Island)",
	"Waitaha, region unspecified",
	"Whakatohea",
	"Whanganui/Rangitikei (Wanganui/Rangitikei) Region, not further defined"
);

$countries = array(
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"British Indian Ocean Territory",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Channel Islands",
	"Chile",
	"China, People's Republic of",
	"Christmas Island",
	"Cocos (Keeling) Islands",
	"Colombia",
	"Comoros",
	"Congo",
	"Congo, the Democratic Republic of the",
	"Cook Islands",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"England",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Faeroe Islands",
	"Falkland Islands",
	"Fiji",
	"Finland",
	"Former Yugoslav Republic of Macedonia (FYROM)",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories",
	"Gabon",
	"Gambia",
	"Gaza Strip/Palestine/West Bank",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hong Kong (Special Administrative Region)",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea, Democratic People's Republic of",
	"Korea, Republic of",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau (Special Administrative Region)",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia, Federated States of",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"Netherlands Antilles",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Ireland",
	"Northern Mariana Islands",
	"Norway",
	"Not Stated",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Passengers' Effects",
	"Peru",
	"Philippines",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Reunion",
	"Romania",
	"Russia",
	"Rwanda",
	"Samoa",
	"Samoa, American",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Scotland",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Ships' Bunkering",
	"Ships' Stores",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"Spain",
	"Sri Lanka",
	"St Helena",
	"St Kitts and Nevis",
	"St Lucia",
	"St Pierre and Miquelon",
	"St Vincent and the Grenadines",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States Minor Outlying Islands",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City State",
	"Venezuela",
	"Viet Nam",
	"Virgin Islands, British",
	"Virgin Islands, United States",
	"Wales",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe"
);

$nzSchools = array(
    "Attended School Not On List",
	"ACG New Zealand International College",
	"ACG Parnell College",
	"ACG Senior College",
	"ACG Strathallan",
	"Akaroa Area School",
	"Albany Junior High School",
	"Albany Senior High School",
	"Alfriston College",
	"Allenvale Special School & Res. Centre",
	"Al-Madinah School",
	"Al-Madinah School",
	"Ambury Park Centre For Riding Therapy",
	"Amuri Area School",
	"Amworth Secondary School",
	"Aorere College",
	"Aotea College",
	"Aparima College",
	"Aquinas College",
	"Arahunga School",
	"Aranui High School",
	"Arohanui Special School",
	"Ashburton College",
	"Athena Montessori College",
	"Attended NZ School Not On List",
	"Auckland Girls' Grammar School",
	"Auckland Grammar",
	"Auckland International College",
	"Auckland Metropolitan College",
	"Auckland Seventh-Day Adventist H.S.",
	"Aurora College (replaces 4033 & 444)",
	"Aurora Girls' Home",
	"Avon Christian College",
	"Avon Christian College",
	"Avondale College",
	"Avonside Girls' High School",
	"Awatapu College",
	"Awatapu School",
	"Awhina School",
	"Baradene College",
	"Bay Of Islands College",
	"Bayfield High School",
	"Beck House",
	"Berkley Normal Middle School",
	"Bethlehem College",
	"Bethlehem College",
	"Birkenhead College",
	"Bishop Viard College",
	"Blind and Low Vision Education Network NZ (Te Kotuituinga Matauranga Pura o Aotearoa)",
	"Blomfield Special School & Resource Ctre",
	"Blue Mountain College",
	"Bollard Ave Girls' Home School",
	"Botany Downs Secondary School",
	"Bream Bay College",
	"Broadwood Area School",
	"Buller High School",
	"Burnside High School",
	"Cambridge High School",
	"Cambridge International College",
	"Cambridge Middle School",
	"Campbell Park School",
	"Campion College",
	"Canterbury Christian College",
	"Carey College",
	"Carey College",
	"Cargill High School",
	"Carlson School (Cerebral Palsy)",
	"Carmel College",
	"Cascade Christian College",
	"Cashmere High School",
	"Catholic Cathedral College",
	"Central Hawkes Bay College",
	"Central Regional Health School",
	"Central Southland College",
	"Chanel College",
	"Cheviot Area School",
	"Children Of Hope New Zealand",
	"Chilton St.James School",
	"Cholmondeley Emergency Home",
	"Christchurch Adventist School",
	"Christchurch Boys' High School",
	"Christchurch Boys' Home School",
	"Christchurch Girls' High School",
	"Christchurch Senior College",
	"Christian Renewal School",
	"Christian School",
	"Christ's College",
	"Church College Of New Zealand",
	"Clareville School",
	"Clendon Teen Parent Unit",
	"Clover Park Middle School",
	"Coastal Taranaki School (replaces 2204",
	"Collingwood Area School",
	"Columba College",
	"Cornell High School",
	"Coromandel Area School",
	"Coromandel Street School",
	"Corran School",
	"Correspondence School",
	"Craighead Diocesan School",
	"Cromwell College",
	"Cullinane College",
	"Dannevirke High School",
	"Darfield High School",
	"Dargaville High School",
	"De La Salle College",
	"Dilworth School",
	"Dingwall Trust School",
	"Diocesan School For Girls",
	"Drury Christian School",
	"Dunstan High School",
	"East Otago High School",
	"Eden Campus",
	"Edgecumbe College",
	"Edgewater College",
	"Edmund Rice College",
	"Educational Unit",
	"Edward Seager School",
	"Elim Christian College",
	"Ellesmere College",
	"Epsom Girls' Grammar School",
	"Epuni Boys' Home School",
	"Erskine College",
	"Excellere College",
	"Fairfield College",
	"Fairhaven School (Napier)",
	"Feilding High School",
	"Felix Donnelly College",
	"Ferndale School (Christchurch)",
	"Fiordland College",
	"Flaxmere College",
	"Forest View High School",
	"Four Avenues Alternative School",
	"Francis Douglas Memorial College",
	"Freyberg High School",
	"Garin College",
	"Geraldine High School",
	"Gisborne Boys' High School",
	"Gisborne Girls' High School",
	"Glendowie College",
	"Glenelg Health Camp School",
	"Glenfield College",
	"Global Indian International School",
	"Gloriavale Christian Community School",
	"Golden Bay High School",
	"Goldfields School",
	"Gore High School",
	"Green Bay High School",
	"Greymouth High School",
	"Greymouth Special School",
	"Hagley Community College",
	"Halswell Residential College",
	"Hamilton Boys' High School",
	"Hamilton Boys' Home",
	"Hamilton Christian School",
	"Hamilton Christian School",
	"Hamilton Collegiate",
	"Hamilton Girls' High School",
	"Hamilton North School",
	"Hamilton's Fraser High School",
	"Hamilton's Fraser High School TPU",
	"Hastings Boys' High School",
	"Hastings Christian School",
	"Hastings Christian School",
	"Hastings Girls' High School",
	"Hato Paora College",
	"Hato Petera College",
	"Hauraki Plains College",
	"Havelock North High School",
	"Hawera Christian Academy",
	"Hawera High School",
	"Hawkes Bay School for Teenage Parents",
	"He Huarahi Tamariki",
	"He Mataariki School for Teen Parents",
	"Health Camp School (Otago-Southland)",
	"Hebron Christian College (Auckland)",
	"Hebron Christian College (Nelson)",
	"Henderson High School",
	"Heretaunga College",
	"High cliff High School",
	"Hill Top School",
	"Hill Top School (Sec Dept) (now part of 4142 Hill Top School)",
	"Hillcrest High School",
	"Hillmorton High School",
	"Hillview Christian School",
	"Hohepa Home School (Christchurch)",
	"Hohepa Home School (Napier)",
	"Hokio Beach School",
	"Hokitika Christian School",
	"Hokjitika Christian School",
	"Home Schooling",
	"Homeleigh Christian School",
	"Hornby High School",
	"Horowhenua College",
	"Howick College",
	"Hukarere",
	"Huntly College",
	"Hurunui College",
	"Hutt International Boys' School",
	"Hutt Valley High School",
	"Immanuel Christian School",
	"Immanuel Christian School",
	"Inangahua College",
	"Independent Middle School",
	"Inglewood High School",
	"International Christian School",
	"International Middle School",
	"Iona College",
	"James Cook High School",
	"James Hargest College (merge of 403",
	"James Hargest High School",
	"John McGlashan College",
	"John Paul College",
	"John Paul II High School",
	"Kadimah College",
	"Kahutia School",
	"Kaiapoi High School",
	"Kaikohe Christian School",
	"Kaikohe Christian School",
	"Kaikorai Valley College",
	"Kaikoura High School",
	"Kaipara College",
	"Kaitaia Abundant Life School",
	"Kaitaia Abundant Life School",
	"Kaitaia College",
	"Kaka Street Special School",
	"Kamahi School",
	"Kamo High School",
	"Kapi-Mana School",
	"Kapiti College",
	"Karamea Area School",
	"Karamu High School",
	"Karanga Mai Young Parents College",
	"Katikati College",
	"Kavanagh College",
	"Kawerau College",
	"Kawerau Teen Parent Unit",
	"Kea Street Specialist School",
	"Kelston Boys' High School",
	"Kelston Deaf Education Centre",
	"Kelston Girls' College",
	"Kerikeri Christian Community School",
	"Kerikeri Christian School",
	"Kerikeri High School",
	"Kimi Ora School",
	"Kimihia Parents' College",
	"King Edward International High School",
	"Kings Christian School",
	"Kings College",
	"Kings College (Christchurch)",
	"Kings High School (Dunedin)",
	"Kingslea School",
	"Kingsway School",
	"Kingsway Secondary School",
	"Kingswell High School",
	"Kohitere School",
	"Kokohuia School",
	"Kowhai School",
	"Kristin School",
	"Kura Teina o Nga Waipupu o Punahau",
	"Kuranui College",
	"Lake Taupo Christian School",
	"Lawrence Area School",
	"Lincoln High School",
	"Lindisfarne College",
	"Linwood College",
	"Liston College",
	"Living Way Learning Centre",
	"Logan Park High School",
	"Long Bay College",
	"Longburn Adventist College",
	"Lynfield College",
	"Lytton High School",
	"Mackenzie College",
	"Macleans College",
	"Mahurangi College",
	"Mairehau High School",
	"Maitai School",
	"Makoura College",
	"Mana College",
	"Mana Tamariki",
	"Manawatu College",
	"Mangakahia Area School",
	"Mangakino Area School",
	"Mangakino High School",
	"Mangere College",
	"Maniapoto School",
	"Maniototo Area School",
	"Manukau Christian School",
	"Manurewa High School",
	"Marcellin College",
	"Marian College",
	"Marist College",
	"Marist College (Invercargill)",
	"Marlborough Boys' College",
	"Marlborough Girls' College",
	"Marsden Christian School",
	"Marsden Christian School",
	"Maru School & Resource Centre",
	"Massey High School",
	"Matamata College",
	"Mataora Girls' Home School",
	"Matarawa Special School",
	"McAuley High School",
	"McKenzie Residential School",
	"McKillop College",
	"Melville High School",
	"Menzies College",
	"Mercury Bay Area School",
	"Mercy College",
	"Merton Street School",
	"Michael Park School",
	"Middlemore Hospital School",
	"Middleton Grange School",
	"MindAlive",
	"Montessori College of Auckland",
	"Moreau College",
	"Morrinsville College",
	"Mosgiel Intermediate",
	"Motueka High School",
	"Mount Hutt College",
	"Mountainview High School",
	"Mt Anglem College",
	"Mt. Hobson Middel School",
	"Mt.Albert Grammar School",
	"Mt.Aspiring College",
	"Mt.Maunganui College",
	"Mt.Richmond School",
	"Mt.Roskill Grammar",
	"Murchison Area School",
	"Naenae College",
	"Napier Boys' High School",
	"Napier Girls' High School",
	"Nayland College",
	"Nelson Christian Academy",
	"Nelson College",
	"Nelson College For Girls",
	"Never Attended A Secondary School",
	"New Plymouth Boys' High School",
	"New Plymouth Girls' High School",
	"Newlands College",
	"Nga Kakano Christian Reo Rua Kura",
	"Nga Taiatea Wharekura",
	"Ngakakano Christian Bilingual School",
	"Ngaruawahia High School",
	"Ngata Memorial College",
	"Northcote College",
	"Northern Health School",
	"Northern Southland College",
	"Northland College",
	"Northland Health Camp School",
	"Oaklynn Special School",
	"Odyssey House School (Auckland)",
	"Odyssey House School (Christchurch)",
	"Okaihau College",
	"Okato College",
	"One Tree Hill College",
	"Onehunga High School",
	"Onewhero Area School",
	"Onslow College",
	"Opihi College (formerly known as Temuka High School)",
	"Opononi Area School",
	"Opotiki College",
	"Opunake High School",
	"Orewa College",
	"Otago Boys' High School",
	"Otago Girls' High School",
	"Otahuhu College",
	"Otaki College",
	"Otaki Health Camp School",
	"Otamatea Christian School",
	"Otamatea Christian School",
	"Otamatea High School",
	"Otorohanga College",
	"Otumoetai College",
	"Oxford Area School",
	"Paeroa College",
	"Pakuranga College",
	"Pakuranga Health Camp School",
	"Palmerston North Boys' High School",
	"Palmerston North Girls' High School",
	"Panguru High School",
	"Papakura High School",
	"Papanui High School",
	"Papatoetoe High School",
	"Paraparaumu College",
	"Parkside School",
	"Parkway College",
	"Patea Area School",
	"Patricia Avenue School",
	"Petone College",
	"Pinehurst School",
	"Pinehurst Secondary School",
	"Piopio College",
	"Pleasant Point High School",
	"Pompallier College",
	"Ponatahi Christian School",
	"Ponatahi Christian School",
	"Porirua College",
	"Prospect College",
	"Pukekohe Christian School",
	"Pukekohe Christian School",
	"Pukekohe High School",
	"Pukeroa Home School",
	"Putaruru College",
	"Putaruru High School",
	"Queen Charlotte College",
	"Queen Elizabeth College",
	"Queen Margaret College",
	"Queen Victoria School",
	"Queens College",
	"Queens High School",
	"Raglan Area School",
	"Rai Valley Area School",
	"Rangi Ruru Girls' School",
	"Rangiora High School",
	"Rangiora New Life School",
	"Rangitahi College",
	"Rangitaiki Independent School",
	"Rangitaiki Independent School",
	"Rangitikei College",
	"Rangitoto College",
	"Raphael House Rudolf Steiner Area School",
	"Rathkeale College",
	"Raukawa School",
	"Raumanga School",
	"Redwood College",
	"Reefton Area School",
	"Reefton School",
	"Reikorangi College",
	"Reporoa College",
	"Riccarton High School",
	"Richmond Christian College",
	"Richmond View Secondary School",
	"Rodney College",
	"Roncalli College",
	"Rongotai College",
	"Rosehill College",
	"Rosehill School",
	"Roselyn School",
	"Rosmini College",
	"Rotorua Bible Baptist Church School",
	"Rotorua Boys' High School",
	"Rotorua Girls' High School",
	"Rotorua Lakes High School",
	"Rotorua School for Young Parents",
	"Roxburgh Area School",
	"Ruapehu College",
	"Ruatoki Kura Tuarua School",
	"Ruawai College",
	"Rudolf Steiner School (Belmont)",
	"Rudolf Steiner School (Chch)",
	"Ruru Special School",
	"Rutherford College",
	"Sacred Heart College (Auckland)",
	"Sacred Heart College (Lower Hutt)",
	"Sacred Heart College (Napier)",
	"Sacred Heart College (Wanganui)",
	"Sacred Heart Girls' College (Chch)",
	"Sacred Heart Girls' College (Ham)",
	"Sacred Heart Girls' College (N.Plymouth)",
	"Salisbury School (Nelson)",
	"Samuel Marsden Collegiate School",
	"Samuel Marsden Collegiate School -Whitby",
	"Sancta Maria College",
	"Sara Cohen School",
	"Scots College",
	"Secondary School Not Known",
	"Selwyn College",
	"Shiloh Christian Academy (Motueka)",
	"Shirley Boys' High School",
	"Sir Edmund Hillary Collegiate",
	"Sir Keith Park School",
	"Solway College",
	"Sommerville School",
	"South Otago High School",
	"South Westland Area School",
	"Southbridge District High School",
	"Southern Cross Campus",
	"Southern Cross Middle School",
	"Southern Lakes Christian School",
	"Southern Lakes Christian School",
	"Southern Regional Health School",
	"Southland Boys' High School",
	"Southland Girls' High School",
	"Spotswood College",
	"Springbank School",
	"St Dominic's School for Deaf",
	"St Mark's Church School",
	"St Mark's Church School (Sec Dept) (Mt V)",
	"St Paul's High School (Dunedin)",
	"St. Andrew's Christian School",
	"St. Andrew's College (Christchurch)",
	"St. Andrew's Middle School (Hamilton)",
	"St. Bedes College",
	"St. Benedicts College",
	"St. Bernard's College",
	"St. Catherines College (Invercargill)",
	"St. Catherines College (Kilbirnie)",
	"St. Cuthbert's College (Epsom)",
	"St. Dominic's College",
	"St. Dominic's College (Henderson)",
	"St. Hildas Collegiate",
	"St. John's College (Hastings)",
	"St. John's College (Hillcrest)",
	"St. Joseph's Maori Girls' College",
	"St. Kentigern College (Pakuranga)",
	"St. Kevins College (Oamaru)",
	"St. Margaret's College",
	"St. Martin's Christian Secondary School",
	"St. Mary's College (Chch)",
	"St. Mary's College (Greymouth)",
	"St. Mary's College (Ponsonby)",
	"St. Mary's College (Wellington)",
	"St. Mary's Diocesan School (Stratford)",
	"St. Matthew's Collegiate (Masterton)",
	"St. Oran's College",
	"St. Patrick's College (Kilbirnie)",
	"St. Patrick's College (Silverstream)",
	"St. Patrick's College (Timaru)",
	"St. Paul's College (Ponsonby)",
	"St. Paul's Collegiate (Hamilton)",
	"St. Peter's College (Epsom)",
	"St. Peter's College (Gore)",
	"St. Peter's College (Palmerston North)",
	"St. Peter's School (Cambridge)",
	"St. Raphaels School (Carterton)",
	"St. Stephen's School (Bombay)",
	"St. Thomas Girls High School",
	"St. Thomas Of Canterbury College",
	"Stratford High School",
	"Stratford High School Teen Parent Unit",
	"Strathallan College",
	"Sunderland School and College",
	"Sunnydene Special School",
	"Sunset Junior High School",
	"Taieri College",
	"Taihape Area School (replaces 184 & 2458)",
	"Taihape College",
	"Taikura Rudolf Steiner School",
	"Taipa Area School",
	"Taita College",
	"Takapuna Grammar School",
	"Tamaki College",
	"Tamariki Special School",
	"Tamatea High School",
	"Tangaroa College",
	"Tangaroa College Teen Parent Unit",
	"Tapawera Area School",
	"Taradale High School",
	"Tararua College",
	"Tau Te Arohanoa Akoranga",
	"Tauhara College",
	"Taumarunui Christian Academy",
	"Taumarunui High School",
	"Taupo Nui- A-Tia College",
	"Tauranga Boys' College",
	"Tauranga Girls' College",
	"Tauraroa Area School",
	"Tawa College",
	"Te Aroha College",
	"Te Aute College",
	"Te Awamutu College",
	"Te Hiranui Special School",
	"Te Kainga Whaiora Children's Health Camp",
	"Te Kauwhata College",
	"Te Kuiti High School",
	"Te Kura Hauora",
	"Te Kura Kaupapa Maori O Hoani Waititi",
	"Te Kura Kaupapa Maori O Huiarau",
	"Te Kura Kaupapa Maori O Kaikohe",
	"Te Kura Kaupapa Maori O Mana Tamariki",
	"Te Kura Kaupapa Maori O Mangere",
	"Te Kura Kaupapa Maori O Nga Mokopuna",
	"Te Kura Kaupapa Maori O Ruamata",
	"Te Kura Kaupapa Maori O Tamaki Nui A Rua",
	"Te Kura Kaupapa Maori O Te Koutu",
	"Te Kura Kaupapa Maori O Te Rawhiti Roa",
	"Te Kura Kaupapa Maori O Te Rito",
	"Te Kura Kaupapa Maori O Te Whanau Tahi",
	"Te Kura Kaupapa Maori O Wairarapa",
	"Te Kura Kaupapa Maori O Waitaha",
	"Te Kura Kaupapa Motuhake O Tawhiuau",
	"Te Kura Maori o Nga Tapuwae",
	"Te Kura Maori o Porirua",
	"Te Kura Maori-a-Rohe o Waiohau",
	"Te Kura O Awarua",
	"Te Kura o Hirangi",
	"Te Kura O Te Rau Aroha",
	"Te Kura o Whakatupuranga Rua Mano",
	"Te Kura Taumata O Panguru",
	"Te Kura Toitu o Te Whati-nui-a-Toi",
	"Te Puke High School",
	"Te Rangi Aniwaniwa",
	"Te Waha o Rerekohu Area School ( merge of 213",
	"Te Waha-O-Rerekohu Area School (now 550)",
	"Te Whakatipuranga (Otumoetai TPU)",
	"Te Whanau O Tupuranga",
	"Te Whanau-A-Apanui Area School",
	"Te Whare Whai Hua Teenage Parent Centre",
	"Te Wharekura O Arowhenua",
	"Te Wharekura o Manurewa",
	"Te Wharekura O Rakaumangamanga",
	"Te Wharekura O Ruatoki",
	"Te Wharekura o Te Kaokaoroa o Patetere",
	"Tenison College",
	"Thames High School",
	"The Bridge Academy",
	"The Catlins Area School",
	"The Corelli School",
	"The Corelli School",
	"The Taieri High School",
	"Tikipunga High School",
	"Timaru Boys' High School",
	"Timaru Girls' High School",
	"Titiro Whakamua",
	"TKKM O Mana Tamariki",
	"TKKM O Ngati Kahungunu Ki Heretaunga",
	"TKKM O Te Ara Hou",
	"TKKM O Te Waiu O Ngati Porou",
	"TKKM o Tupoho",
	"TKKM Te Ahureinga o Whakatohea",
	"Tokanui Special School",
	"Tokomairiro High School",
	"Tokoroa High School",
	"Tolaga Bay Area School",
	"Tongariro High School",
	"Tongariro School (formerly Turangi ki Tongariro Area School)",
	"Totara College Of Accelerated Learning",
	"Totara College of Accelerated Learning",
	"Trident High School",
	"TTKM O Whakarewa I Te Reo Ki Tuwharetoa",
	"Tuakau College",
	"Tuatapere Community College",
	"Turakina Maori Girls' College",
	"Tweedsmuir Junior High School",
	"Twizel Area School",
	"Twizel High School",
	"Tyndale Park Christian School",
	"Unlimited Paenga Tawhiti",
	"Upper Hutt College",
	"Van Asch Deaf Education Centre",
	"Verdon College",
	"Victoria Christian Academy",
	"Villa Maria College",
	"Waiheke Area School",
	"Waiheke High School",
	"Waihi College",
	"Waikato Diocesan School For Girls",
	"Waikohu College",
	"Waimate High School",
	"Waimate North Christian School",
	"Waimea College",
	"Waimokoia Residential School",
	"Wainuiomata Christian College",
	"Wainuiomata College",
	"Wainuiomata High School",
	"Waiopehu College",
	"Wairarapa College",
	"Wairarapa Teen Parent Unit",
	"Wairau Valley School",
	"Wairoa College",
	"Waitaha Learning Centre",
	"Waitakere College",
	"Waitaki Boys' High School",
	"Waitaki Girls' High School",
	"Waitara High School",
	"Waiuku College",
	"Waka Ora Boys' Home School",
	"Wakatipu High School",
	"Wanaka Area School",
	"Wanganui City College",
	"Wanganui Collegiate School",
	"Wanganui Girls' College",
	"Wanganui High School",
	"Wa-Ora School",
	"Warea School",
	"Waverley High School",
	"Wellington College",
	"Wellington Diocesan School For Girls",
	"Wellington East Girls' College",
	"Wellington Girls' College",
	"Wellington High School & Com Center",
	"Wentworth College",
	"Weraroa Hospital School",
	"Wesley College",
	"Wesleydale Boys' Home",
	"West City Christian College",
	"Westbridge Residential School",
	"Western City Christian School",
	"Western Heights High School",
	"Western Springs College",
	"Westlake Boys' High School",
	"Westlake Girls' High School",
	"Westland High School",
	"Westminster Christian School",
	"Westmount School",
	"Weymouth Centre School",
	"Whaiora School",
	"Whakatane High School",
	"Whakatipuria Teen Parent Unit",
	"Whangamata Area School",
	"Whangaparaoa College",
	"Whangarei Boys' High School",
	"Whangarei Girls' High School",
	"Whangaroa College",
	"Wharera Special School Group",
	"William Colenso College",
	"Wilson School",
	"Windermere Christian College",
	"Woodford House",
	"Xavier College",
	"Zayed College for Girls"
);

?>